server:
  port: 8090
spring:
  application:
    name: example
  cloud:
    nacos:
      config:
        group: DEFAULT_GROUP
        server-addr: 192.168.1.5:8848
  config:
    import:
      - optional:nacos:hello