server:
  port: 8001
spring:
  application:
    name: echo-server
  cloud:
    nacos:
      config:
        group: DEFAULT_GROUP
        server-addr: 192.168.1.5:8848
  config:
    import:
      - optional:nacos:echo_server.yml
      - optional:nacos:hello?group=DEFAULT_GROUP